trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'Celerik Infra (49dfe249-d68f-4796-9fb0-94ecef43d4d7)'
        KeyVaultName: 'kv-getaclub-prod'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: replacetokens@3
      displayName: Replace tokens to application-prod.yml
      inputs:
        targetFiles: '**/application-prod.yml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{{'
        tokenSuffix: '}}'
        useLegacyPattern: false
        enableTelemetry: true 
    
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        tasks: 'build'
    - task: CopyFiles@2
      displayName: 'Copy Files to: Wireframe Directory on development server'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)
        ArtifactName: 'drop'
    - task: CmdLine@2
      inputs:
        script: cd '$(Build.ArtifactStagingDirectory)'; ls

